### PR TITLE
Use Parabolic SAR indicator to only buy when bullish trend

### PR DESCRIPTION
**Pull request by vertti**
This PR introduces "Parabolic SAR" indicator. When the indicator is below close price, the trend is bullish. Buy signal rule is changed so that we only buy when PSAR shows that trend is up. This should remove lots of risky downtrend buy signals.

screenshot 2017-09-01 21 41 38

I used a widely used library `TA-lib` to get the PSAR indicator. This library contains 150 other indicators also. What I would like to do (but which is not done yet), is get rid of both `stockstats` and the manual calculation of StochRSI, as both MACD and StochRSI are available from `TA-lib`. If you @gcarq feel like taking a stab at removing the `stockstats` in favor of TA-lib + regular pandas, that would be awesome.

### CODE REVIEW

**Comment by gcarq** [comment]
Looks promising. I'm fine with removing stockstats, I wasn't aware that TA-lib exists :-)

**Comment by vertti** [comment]
Alright, looked into this a little more. It seems I can get rid of both the manually calculated StochRSI as well as the whole stockstats lib with just few lines of TA-lib code.

I can do the changes but I'd prefer to do them in a separate PR if you merge this first?

**Comment by gcarq** [comment]
Can you please resolve the conflict in `requirements.txt` and also adapt the Dockerfile to install TA-lib? If it's resolved I'm merging it.

**Comment by vertti** [comment]
Merged master, resolved conflicts and added TA-lib installation to `Dockerfile`.

**Pull request merged**
