### PR TITLE
Fixing daily profit,

### PR DESCRIPTION
**Pull request by jblestang**
Daily profit was miscalculated, the time part of the time should not be taken to get the previous day and the next day, this commit remove this. Profit and Daily commands are now very close when summing the results of every day profit.

### CODE REVIEW

**Comment by glonlas** [comment]
Thanks for the PR, I will check it in detail. Between this PR break the unit tests. Please do not forget to update them.

**Comment by jblestang** [comment]
Which test is broken? They are all green here

**Comment by glonlas** [comment]
You are right. From my phone, the page told me a check failed.

**Comment by glonlas** [comment]
Thank you for merging it. I was to test it and merge it as well. I will add additional unit test to cover multi days profit case.

**Pull request merged**
