### PR TITLE
Add loss instead of profit

### PR DESCRIPTION
**Pull request by seansan**
plz check my code

### CODE REVIEW

**Comment by glonlas** [comment]
Please add a unitest to test this behavior. It will ensure it will not be broken in the future.

Thanks

**Comment by vertti** [comment]
This breaks an existing unit test.

**Comment by jblestang** [comment]
PR #276 should cover your requests

**Comment by glonlas** [comment]
This feature was included in the PR #276 from @jblestang.
Thank you @seansan for contributing and help the bot.

I close this PR.

**Pull request closed without merging**
