### PR TITLE
replace pymarketcap with coinmarketcap

### PR DESCRIPTION
**Pull request by xmatthias**
## Summary
Replace pymarketcap with coinmarketcap to avoid depending on cython which was introduced in the lastest version.

replaces PR #559

## Quick changelog

- replace pymarketcap with coinmarketcap

## Reason
cython is a very heavy dependency in my eyes.
Also, we only use the ticker-function from pymarketcap, so a simple library (with very simple dependencies) will suffice.

### CODE REVIEW

**Comment by glonlas** [comment]
Have you tried to run pytest without Internet connections? I had to mockup Pymarketcap everywhere because without or bad connections the lib waits for a timeout and it added 2sec to every test. 

Most of the time mock of pymarketcap is to reduce unit test durations.

**Comment by xmatthias** [comment]
Honestly, i don't understand why `_cache_symbols` was mocked - it's not used anywhere directly, and in my understanding of MagicMock - if the return-value is mocked, then the function is not executed but returns immediately.

i tired without network now and there was no noticable delay.

**Comment by glonlas** [comment]
Honnestly I do not recall. If you do not see any difference with and without the mock, drop it :) 
Less code more fun :)

**Comment by xmatthias** [comment]
the new library (coinmarketcap) does not have the `_cache_symbols` function.
looking at the source of pymarketcap, it did work differently - it made a call in init() - which coinmarketcap does not, which explains the different results you were seeing without network.

**Pull request merged**
