### PR TITLE
Better buy and sell strategy

### PR DESCRIPTION
**Pull request by rybolov**
Added Plus and Minus Directional Indicator and Directional Movement into dataframe.
Buy if at the low end of normal range and the price is increasing.
Buy into extreme gains regardless of if it's on the low part of the range.
Avoid buying when the price is on a long decrease even if it's low.
Sell anytime the price is above the top end of normal range and the momentum slows.
Sell on an extreme drop.

### CODE REVIEW

**Comment by vertti** [comment]
With our current backtesting data, this strategy performs considerably worse than our current strategy, producing only half of the profits and less than half in average profits.

Your strategy:
```
pair         buy count  avg profit    total profit       avg duration
---------  -----------  ------------  ---------------  --------------
BTC_BCC            145  1.52%         2.20260693 BTC            39.24
BTC_ETH            225  -0.45%        -1.00312430 BTC           65.18
BTC_DASH           281  0.20%         0.55410963 BTC            37.65
BTC_POWR            15  0.49%         0.07283243 BTC            30.33
BTC_ETC            116  0.37%         0.42401536 BTC            33.97
BTC_VTC            118  1.10%         1.30119933 BTC            38.64
BTC_WAVES          231  -0.34%        -0.78409676 BTC           36.88
BTC_LSK            204  0.16%         0.32081516 BTC            58.04
BTC_XLM            151  0.86%         1.30059812 BTC            34.9
BTC_OK              82  1.18%         0.96904451 BTC            37.87
TOTAL             1568  0.34%         5.35800041 BTC            43.77
```

and our current strategy:

```
pair         buy count  avg profit    total profit       avg duration
---------  -----------  ------------  ---------------  --------------
BTC_BCC             11  0.01%         0.00157285 BTC           155.45
BTC_ETH             86  -0.24%        -0.20455227 BTC          281.74
BTC_DASH            71  0.05%         0.03855389 BTC           288.24
BTC_POWR            20  3.67%         0.73439176 BTC            51
BTC_ETC            121  0.76%         0.92132032 BTC           139.3
BTC_VTC            148  1.38%         2.04443323 BTC           121.96
BTC_WAVES          240  0.73%         1.74263834 BTC           282.5
BTC_LSK            241  0.75%         1.80627143 BTC           194.52
BTC_XLM            230  0.76%         1.74894345 BTC           193.22
BTC_OK             109  1.51%         1.64579185 BTC           117.8
TOTAL             1277  0.82%         10.47936485 BTC          199.13
```

**Comment by rybolov** [comment]
This strategy against the data in develop, I get this:

pair         buy count  avg profit    total profit       avg duration
---------  -----------  ------------  ---------------  --------------
BTC_BCC            145  0.41%         0.58991133 BTC            34.9
BTC_ETH            225  -0.46%        -1.04220851 BTC           59.24
BTC_DASH           281  0.20%         0.57321556 BTC            36.19
BTC_POWR            12  0.72%         0.08584049 BTC            18.33
BTC_ETC            116  0.59%         0.68336771 BTC            31.85
BTC_VTC            118  0.58%         0.67972294 BTC            28.73
BTC_WAVES          231  -0.49%        -1.13668355 BTC           32.42
BTC_LSK            204  -0.25%        -0.51220271 BTC           51.4
BTC_XLM            151  0.72%         1.09431044 BTC            33.11
BTC_OK              82  0.98%         0.80088750 BTC            36.34
TOTAL             1565  0.12%         1.81616120 BTC            39.5


And the original strategy is this:
pair         buy count  avg profit    total profit       avg duration
---------  -----------  ------------  ---------------  --------------
BTC_BCC             11  -1.65%        -0.18157934 BTC          111.36
BTC_ETH             86  -0.90%        -0.77483424 BTC          204.01
BTC_DASH            71  -0.06%        -0.04335750 BTC          201.76
BTC_POWR            20  0.61%         0.12191180 BTC            25.5
BTC_ETC            121  0.88%         1.06139286 BTC            81.16
BTC_VTC            148  0.37%         0.54667916 BTC            43.48
BTC_WAVES          240  -0.58%        -1.39394340 BTC          107.71
BTC_LSK            241  -0.14%        -0.34743820 BTC          101.99
BTC_XLM            230  0.57%         1.30390892 BTC            76.17
BTC_OK             109  0.80%         0.87304021 BTC            66.01
TOTAL             1277  0.09%         1.16578027 BTC            97.89
.

**Comment by chrisapril** [comment]
when i use the develop default config i get this:

 Using ticker_interval: 5 ...
Using local backtesting data (ignoring whitelist in given config)...
Using stake_currency: BTC ...
Using stake_amount: 0.01 ...
Measuring data from 2017-10-25T23:05:00+00:00 up to 2017-11-14T23:00:00+00:00 ...
====================== BACKTESTING REPORT ======================================


pair         buy count  avg profit    total profit       avg duration
---------  -----------  ------------  ---------------  --------------
BTC_BCC             11  -1.65%        -0.18157934 BTC          111.36
BTC_ETH             86  -0.90%        -0.77483424 BTC          204.01
BTC_DASH            71  -0.06%        -0.04335750 BTC          201.76
BTC_POWR            20  0.61%         0.12191180 BTC            25.5
BTC_ETC            121  0.88%         1.06139286 BTC            81.16
BTC_VTC            148  0.37%         0.54667916 BTC            43.48
BTC_WAVES          240  -0.58%        -1.39394340 BTC          107.71
BTC_LSK            241  -0.14%        -0.34743820 BTC          101.99
BTC_XLM            230  0.57%         1.30390892 BTC            76.17
BTC_OK             109  0.80%         0.87304021 BTC            66.01

TOTAL             1277  0.09%         1.16578027 BTC            97.89


how do you get  10.47936485 BTC ??

**Comment by vertti** [comment]
Yeah, my mistake :( I had still -40% stop loss in my `config.json`. I was too used to getting the correct setting from test settings, not my own config.

**Pull request merged**
