### PR TITLE
Backtesting and hyperopt unit tests

### PR DESCRIPTION
**Pull request by vertti**
First set of unit tests for hyperopt and some more for backtesting.

### CODE REVIEW

**Comment by glonlas** [comment]
Will it be possible to squash the commit before merging?

**Comment by shusso** [comment]
Please no re-writing of history :)

**Comment by vertti** [comment]
If the history does not look readable, then it should be rewritten with interactive rebase, fixup, reword etc. But squashing is a bad idea. Keeping distinct atomic commits that change one and only one small thing, when possible, is much preferable, when later you want to understand what was done, use bisect the braking change etc etc.

**Comment by gcarq** [comment]
@glonlas @vertti @shusso I personally prefer squash commits over merge commits, because it makes it much easier to write good changelogs. Each individual commit message is still part of the squash commit message and since a PR should only cover one particular feature/change it doesn't matter to have all the developer thoughts about that feature as a commit instead a commit message.

In my opinion keeping atomic commits only makes sense if you prefix each commit with some meaningful text like it's done in the linux kernel tree, otherwise if you just look at the commit history you have no clue what is going on.

Re-writing history shouldn't be possible once it's merged, develop and master are protected :-)

**Comment by vertti** [comment]
Alright, I still disagree but squashed the PR to much fewer commits that still make sense.

**Pull request merged**
