### PR TITLE
Backtesting

### PR DESCRIPTION
**Pull request by vertti**
Runs a test where I:
- inject static data downloaded from Bittrex to our analysis and find buy signals
- simulate doing a buy on all the found signals, continue forwards until sell criteria is met
- record each buy/sell combo
- write a report of average buy/signal profits and durations

Currently the report looks pretty depressing when it comes to how the bot trades:
```
====================== BACKTESTING REPORT ================================
For currency btc-neo:
Made 50 buys. Average profit -0.4%. Total profit was -0.190. Average duration 738.8 mins.
For currency btc-eth:
Made 56 buys. Average profit 1.3%. Total profit was 0.745. Average duration 3821.3 mins.
For currency btc-omg:
Made 50 buys. Average profit -2.2%. Total profit was -1.115. Average duration 958.9 mins.
For currency btc-edg:
Made 40 buys. Average profit 1.1%. Total profit was 0.457. Average duration 267.5 mins.
For currency btc-pay:
Made 44 buys. Average profit -1.2%. Total profit was -0.513. Average duration 810.1 mins.
For currency btc-pivx:
Made 45 buys. Average profit -2.3%. Total profit was -1.052. Average duration 1173.1 mins.
For currency btc-qtum:
Made 39 buys. Average profit -0.8%. Total profit was -0.313. Average duration 659.7 mins.
For currency btc-mtl:
Made 38 buys. Average profit -2.6%. Total profit was -0.991. Average duration 911.4 mins.
For currency btc-etc:
Made 53 buys. Average profit -0.8%. Total profit was -0.407. Average duration 1580.2 mins.
For currency btc-ltc:
Made 39 buys. Average profit -0.1%. Total profit was -0.050. Average duration 1809.5 mins.
TOTAL OVER ALL TRADES:
Made 454 buys. Average profit -0.8%. Total profit was -3.428. Average duration 1349.6 mins.
```

### CODE REVIEW

**Comment by vertti** [comment]
The backtesting uses the injection and mocking from Python unittests, but the test is slow and not really a unit test, so it is not run by default. To run it, you have to set environment variable `BACKTEST`. To run only the backtesting with pytest, use:

```
BACKTEST=true pytest -s test/test_backtesting.py
```

**Comment by xsmile** [comment]
I have been experimenting with freqtrade for several days (thanks for it btw) and ran backtesting a few times. I think it does not behave like the real version and exceeds the concurrent trade limit of 1 for each market, placing way too many buy orders.
The total profits skyrockets if you greatly increase the ROI values and add a `stoploss` of `-0.5` to the config dictionary which is suspicious.

**Comment by vertti** [comment]
@xsmile true, it does not care about the trade limit. Now, for realistic simulation it should. It should also add delays etc. But for training the best possible buy strategy, you want as much data as possible and the concurrent buy limit would cut down on the number of purchases made so we would have less info on how often it makes a good purchase vs bad purchase.

I noticed the same with `stop_loss`, it seems that having an aggressive `stop_loss` might not be such a good idea.

So yes you are correct in that this is not a fully realistic simulation. Consider it an MVP of backtesting. It is useful in comparing the buy strategy and as long as we do not have a buy strategy that gives consistently winning buys, our bot is not worth much. After that we can add more constraints and realistic twists to the backtesting.

Pull requests for improving the strategies or backtesting are also more than welcome :)

**Comment by xsmile** [comment]
Thank you for the explanation @vertti.

Will do, if I manage to write something useful. First I need to read up on pandas and sqlalchemy.

**Comment by shusso** [comment]
after testing this few times, looks pretty solid.

If you don't care about the output, and want to see the results faster, I'd comment out this [line](https://github.com/gcarq/freqtrade/pull/29/files#diff-5bc02cefb3ea9e27f1a6776eabd1935dR128):

```
BACKTEST=true pytest -s test/test_backtesting.py
...
real    0m39.401s
user    0m38.402s
sys     0m0.441s
```

compared to in this PR:

```
time BACKTEST=true pytest test/test_backtesting.py
..
real    0m53.952s
user    0m51.692s
sys     0m1.640s
```
vs.
```
BACKTEST=true pytest -s test/test_backtesting.py
...
real    1m56.475s
user    1m36.321s
sys     0m3.969s
```

**Pull request merged**
