### PR TITLE
Import numpy missing, used for fisger and other

### PR DESCRIPTION
**Pull request by seansan**
Thank you for sending your pull request. But first, have you included
unit tests, and is your code PEP8 conformant? [More details](https://github.com/gcarq/freqtrade/blob/develop/CONTRIBUTING.md)

## Summary
Explain in one sentence the goal of this PR

Solve the issue: #___

## Quick changelog

- <change log #1>
- <change log #2>

## What's new?
*Explain in details what this PR solve or improve. You can include visuals.*

### CODE REVIEW

**Comment by shusso** [comment]
Thanks for the PR @seansan 

Is numpy actually being used in analyze currently?
```
2.01s$ flake8 freqtrade
freqtrade/analyze.py:10:1: F401 'numpy' imported but unused
```

**Comment by seansan** [comment]
​it is commented out fisher​

**Comment by shusso** [comment]
If it is commented out, then it is not used

**Comment by seansan** [comment]
​this is clear ;) but when you uncomment it you run into problems. A
solution would be to ​
- comment out import numpy (by default)
- add a comment to the numpy required dataframe mentioning to also
uncomment the numpy import

- or just import numpy: I mean it is also in requirements.txt ...

**Comment by shusso** [comment]
> - comment out import numpy (by default)

Wouldn't it be easier to import it when you use it?

> - or just import numpy: I mean it is also in requirements.txt ...

If you import numpy then you need to use it also somewhere otherwise
```
$ flake8 freqtrade
freqtrade/analyze.py:10:1: F401 'numpy' imported but unused
```

**Comment by gcarq** [comment]
Please don't add imports which are not used. I think this will be resolved automatically once we implement a more modular system for strategies

**Comment by glonlas** [comment]
I am pushing in few days a new way to implement strategy, this PR will be obsolete. 

For this reason I close the PR.

**Pull request closed without merging**
