### PR TITLE
Custom random-parameter search with regex output and script.

### PR DESCRIPTION
**Pull request by MoonGem**
Thank you for sending your pull request. But first, have you included
unit tests, and is your code PEP8 conformant? [More details] (not sure) (https://github.com/gcarq/freqtrade/blob/develop/CONTRIBUTING.md)

## Summary
Explain in one sentence the goal of this PR
Try and eliminate hyperopt while threading and doing the same thing.
Solve the issue: #___
Hyperopt.
## Quick changelog

Added "random" folder of items needed swapped to search for random parameters, works good with 32 threads. (or one thread per core)
## What's new?
*Explain in details what this PR solve or improve. You can include visuals.* 
Threaded fake hyperopt. Dropped into user_data

### CODE REVIEW

**Comment by MoonGem** [comment]
Green candle looks lit on default conf.js

I get output like this:

```
total better profit paremeters:
0.05489668
~~~~~~~~~~~~~~~~~~~~~~~~~\nThe Parameters Enabled Are As Follows!!!:  ['[fastd][enabled]']\n~~~~~~~~~~~~~~~~~~~~~~~~~
  :16 XXX\nFASTD Value  :9 XXX\nADX Value  :13 XXX\nRSI Value  :91
  :9 XXX\nADX Value  :13 XXX\nRSI Value  :91
  :13 XXX\nRSI Value  :91
  :91
total better profit paremeters:
0.35118478
~~~~~~~~~~~~~~~~~~~~~~~~~\nThe Parameters Enabled Are As Follows!!!:  ['[macd][enabled]']\n~~~~~~~~~~~~~~~~~~~~~~~~~
  :39 XXX\nFASTD Value  :56 XXX\nADX Value  :54 XXX\nRSI Value  :27
  :56 XXX\nADX Value  :54 XXX\nRSI Value  :27
  :54 XXX\nRSI Value  :27
  :27
total better profit paremeters:
3.68849698
~~~~~~~~~~~~~~~~~~~~~~~~~\nThe Parameters Enabled Are As Follows!!!:  ['[green_candle][enabled]']\n~~~~~~~~~~~~~~~~~~~~~~~~~
  :85 XXX\nFASTD Value  :34 XXX\nADX Value  :2 XXX\nRSI Value  :44
  :34 XXX\nADX Value  :2 XXX\nRSI Value  :44
  :2 XXX\nRSI Value  :44
  :44
```

**Comment by MoonGem** [comment]
Updated so the script output looks like this:
```
/home/owner/freqtrade
total better profit paremeters:
0.00041559
~~~~~~~~~~~~~~~~~~~~~~~~~\nThe Parameters Enabled Are As Follows!!!:  ['[htsine][enabled]', '[has][enabled]', '[macd][enabled]']\n~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~
Only enable the above settings, not all settings below are used!
~~~~~~
~~~MFI~~~
  :36 XXX\nFASTD Value  :46 XXX\nADX Value  :100 XXX\nRSI Value  :82
~~~FASTD~~~
  :46 XXX\nADX Value  :100 XXX\nRSI Value  :82
~~~ADX~~~
  :100 XXX\nRSI Value  :82
~~~RSI~~~
  :82
total better profit paremeters:
0.15977369
~~~~~~~~~~~~~~~~~~~~~~~~~\nThe Parameters Enabled Are As Follows!!!:  ['[macd_below_zero][enabled]']\n~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~
Only enable the above settings, not all settings below are used!
~~~~~~
~~~MFI~~~
  :58 XXX\nFASTD Value  :23 XXX\nADX Value  :20 XXX\nRSI Value  :42
~~~FASTD~~~
  :23 XXX\nADX Value  :20 XXX\nRSI Value  :42
~~~ADX~~~
  :20 XXX\nRSI Value  :42
~~~RSI~~~
  :42
```

**Comment by glonlas** [comment]
Hello,

Could you explain the intention behind this PR, I do not understand what you try to solve. 
In addition, it will be great to have a documentation on how to use it.

**Comment by MoonGem** [comment]
Ok, I'm going to close. I have a newer fork. :)

I won't PR it but it uses python parallel to run hyperopt "random" settings over all the triggers and parameters. Works great for my 32 core machine. If you want to check out the mod go here:  https://github.com/MoonGem/freqtrade/tree/develop/parallel

**Pull request closed without merging**
