### PR TITLE
Support multiple tickers

### PR DESCRIPTION
**Pull request by jblestang**
## Summary
This PR enable the use and configuration of the 1m, 5m, 30 min, 60 min and 1 day ticker

## Quick changelog

- added the ticker interval in the config file
- unit test for the 30 minute ticker and unit tests updated to specify the ticker
- added the ticker interval in the graph name

### CODE REVIEW

**Comment by kryofly** [comment]
This is really great!
It enables beginning to develop multi-timeframe strategies, like buy when RSI > 30 at both 1hour and 5min.
I'll throw my eyeball at it, if it help the review process.
Thanks!

**Comment by jblestang** [comment]
You only have one ticker at the time that is configurable in the conf file.

**Comment by kryofly** [comment]
Great! I found only costmetics. But I got an exception if running freqtrade with dry-run.


```

2018-01-16 09:41:19,151 - freqtrade - ERROR - Got fatal exception!
Traceback (most recent call last):
  File "/home/cryptoc/github-freqtrade/freqtrade/main.py", line 461, in main
    interval=_CONF.get('ticker_interval', 5)
  File "/home/cryptoc/github-freqtrade/freqtrade/misc.py", line 82, in throttle
    result = func(*args, **kwargs)
  File "/home/cryptoc/github-freqtrade/freqtrade/main.py", line 82, in _process
    state_changed = create_trade(float(_CONF['stake_amount']), interval)
  File "/home/cryptoc/github-freqtrade/freqtrade/main.py", line 308, in create_trade
    if get_signal(_pair, SignalType.BUY, interval):
  File "/home/cryptoc/github-freqtrade/freqtrade/analyze.py", line 289, in get_signal
    ticker_hist = get_ticker_history(pair, interval)
  File "/home/cryptoc/github-freqtrade/.env/lib/python3.6/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/home/cryptoc/github-freqtrade/freqtrade/exchange/__init__.py", line 143, in get_ticker_history
    return _API.get_ticker_history(pair, tick_interval)
  File "/home/cryptoc/github-freqtrade/freqtrade/exchange/bittrex.py", line 151, in get_ticker_history
    raise ValueError('Cannot parse tick_interval: {}'.format(tick_interval))
ValueError: Cannot parse tick_interval: 5

```

Cosmetics:

`a/scripts/plot_dataframe.py`
`+        '-i', '--interval',`
`+        default = '5',`
`+        type = int,`

string vs int
Also, maybe use '--ticker-interval' as in misc.py to be consistent to the user.

`+++ b/config.json.example`
`+    "ticker_interval": "5",`
`+++ b/freqtrade/tests/conftest.py`
`+        "ticker_interval": "5",`
`diff --git a/freqtrade/misc.py b/freqtrade/misc.py`
`+        'ticker_interval': {'type': 'string', 'enum': ['1', '5', '30', '60', '1440']},`

Why use string type?



`+++ b/freqtrade/misc.py`
`+                'interval': {'type': 'integer'}`
`+++ b/freqtrade/main.py`
`+                    interval=_CONF.get('ticker_interval', 5)`
From config would get a string, but default would get an int.

I dont understand how this internals thing works. But do we need interval in it? I'm thinking that _process always have access to _CONF['ticker_interval']

**Comment by jblestang** [comment]
Yes when not set un the conf it should cast the string to int. We use a string si that we cannot weave an enun with only the subset of allowed values by Bittrex so that the user cannot use other values

**Comment by kryofly** [comment]
Oh, conf enum is some sort of json-schema enum? And json only handles floats, so it can't be enforced?

Anyhow, could you check that exception. We are passing a tick_interval as a string to bittrex.pl::get_ticker_history()

**Comment by glonlas** [comment]
@jblestang could you please rebase develop?

**Pull request merged**
