### PR TITLE
take fees into account & sell amount equal to amount purchased

### LINKED ISSUE #22: Sell amount equal to amount purchased
At the moment, the bot sells whatever the balance is for the given pair on the exchange. It would be nice to have an option to sell only the amount of coin previously purchased by the bot. This way, freqtrade won't accidentally mess with whatever trades I am doing manually on the side.

### PR DESCRIPTION
**Pull request by gcarq**
This PR got a little bit bigger than expected.

It adds a central function for price calculation, which respects fees.
The fee gets persisted in `Trade`. I've also added a `update` method to `Trade` which updates `open_rate, close_rate, etc.` to the actual selected prices and amount.  As a side effect we can now be sure to only sell the balance we bought earlier and not the whole balance for a specific coin (the fix is also included in this PR).

I also bumped the version number for the sqlite file to `tradesv3.sqlite` because it isn't backward compatible

EDIT: resolves #22 and #56

### CODE REVIEW

**Comment by shusso** [comment]
@gcarq I think there is a slight percentage mis-match somewhere. In telegram
```
BITTREX: Selling BTC/OMG with limit 0.000860 (profit: ~2.31%)
```

And when issuing `/performance` one gets
```
BTC_OMG 8572.77%
```

with git version
```
[2017-11-01] <5ad25a6> (gcarq) fix percentage formating in execute_sell
```

**Comment by gcarq** [comment]
@shusso Thanks for testing it out, did you run it with `dry_run: true`?

**Comment by shusso** [comment]
@gcarq yes, forgot to mention I ran it with dry_run enabled

**Comment by gcarq** [comment]
@shusso I've added a note to inform users about the mocked values with `dry_run=True` in `/telegram` and `/profit` handler

**Pull request merged**
