### PR TITLE
Fix/Update status table to actually show a table again

### PR DESCRIPTION
**Pull request by seansan**
Fix/Update status table to actually show a table again
- shorten pairt strip off base currency
- shorten % to 1 decimal
- shorten humanize remove space, change min->m
- Align left
- Reduce header names (header key lenght + 2 = column size)

Fixes https://github.com/gcarq/freqtrade/issues/462

### CODE REVIEW

**Comment by glonlas** [comment]
Also look at the unitest and flake8. Some are broken. Let me know if you need guidance to run them on your computer.

**Comment by seansan** [comment]
This is above my pay grade

Haven’t used either (yet)

**Comment by seansan** [comment]
I have been using this for some days now and very happy with it. Coding can be improved of course, but my contribution was mainly trying to reduce the string width ... 

todo:
I do see that humanize als writes out "month" as full and this should also be abbreviated

**Comment by vertti** [comment]
Closing this for now, no activity in months.

**Pull request closed without merging**
