### PR TITLE
Read .gzip files in testdata/

### PR DESCRIPTION
**Pull request by rybolov**
In loading a ticker pair file for backtesting and hyperopts:
Checks to see if a .json.gzip ticker file exists.  If so, loads that as the pair.
Then checks to see if .json file exists. If so, loads that as the pair.

### CODE REVIEW

**Comment by kryofly** [comment]
This is great!
I have a related script that converts a binary lzma compressed ticker history into a freqtrade compatible data structure. I guess gzip is widely available than lzma. I had to recompile my python.

**Comment by glonlas** [comment]
Hello @rybolov,
Please add unit tests to cover the logic you are adding.

**Comment by rybolov** [comment]
@glonlas Tests added. =)

**Comment by rybolov** [comment]
@kryofly It's because I [use gzip data here](https://github.com/rybolov/freqtrade-data).

**Comment by glonlas** [comment]
Thank you for the unit test. 
Now we have to please Flake8, Could you please add a space from of the # in your comments.
```
freqtrade/tests/optimize/test_optimize.py:205:5: E265 block comment should start with '# '
freqtrade/tests/optimize/test_optimize.py:207:5: E265 block comment should start with '# '
freqtrade/tests/optimize/test_optimize.py:210:5: E265 block comment should start with '# '
```

**Comment by rybolov** [comment]
@glonlas Done.

**Comment by glonlas** [comment]
Looks good. thanks for the PR

**Pull request merged**
