### PR TITLE
Add support for more exchanges with ccxt

### PR DESCRIPTION
**Pull request by enenn**
## Summary
Work in progress for adding support for multiple exchanges using the [ccxt library](https://github.com/ccxt/ccxt). 

ccxt is a multi-exchange trading library that supports many different exchanges though a unified API, including Binance and Bittrex.  Transistioning to this library from [python-bittrex](https://github.com/ericsomdahl/python-bittrex) will take some work since much of the code is adapted to use the bittrex API data structures. 

I'm posting this PR to get some feedback on the stuff I've already done and help with completing the rest of the work. All tests pass, PEP8 compliant

A major change is switching the default exchange to Binance from Bittrex, since Bittrex is currently closed for registrations which makes it harder to test the API. The active exchange can be changed easily from the config, but Binance is used for tests and fetching backtest data.

## Quick changelog

- Replace python-bittrex with ccxt
- Remove `get_wallet_health` and `get_market_summaries` methods in favor of `get_markets`
- Change default exchange to Binance
- Change pair format from "BTC_XXX" to "XXX/BTC" in configs, to "XXX_BTC" for files to match the [common standard](https://en.wikipedia.org/wiki/Currency_pair)
- Update old exchange tests to work with ccxt
- Change `ticker_interval` format from integer in minutes to string (1m, 5m, 1d, ...)
- Encapsulate all exceptions from ccxt to be able to use the same exception types in the entire project
## Todo

- Rewrite `exchange.get_pair_detail_url`. Won't be part of ccxt (see [ccxt#108](https://github.com/ccxt/ccxt/issues/108))
- Fetch backtest data limited to 500 candles on Binance. Maybe fetch from some other exchange?

### CODE REVIEW

**Comment by glonlas** [comment]
Why removing Bittrex reference and not composing with it?
Why changing the pair format?

**Comment by shusso** [comment]
Thanks for the PR @enenn good stuff 👍 

One note
> Change default exchange to Binance

There are quite alot of existing bot users who are using Bittrex, so the default exchange should stay as Bittrex.


> Why changing the pair format?

@glonlas I think bittrex is a bit wonky on the pair format per the normal `BaseCurrency/QuoteCurrency ` format. CCXT will do magic under the hood to make all the exchanges convert to that format, read [more](https://github.com/ccxt/ccxt/wiki/Manual#market-structure)

**Comment by vertti** [comment]
Bittrex definitely needs to be ripped out. Why would we want to keep adding complexity when we can simply remove it and let the external library handle it?

Why changing the pair format? Well because the new format is the correct one and one we currently use is an oddity that is incorrect and only used by Bittrex.

The whole exchange abstraction we currently have in the bot is ugly, overengineered monster that can and should be completely removed and replaced with like 5 lines of ccxt specific code ("take exchange name from config, instantiate correct exchange from ccxt, then use ccxt exchange abstraction for everything").

**Comment by enenn** [comment]
I think @vertti summarised my thoughts quite nicely. A lot of the code for the bot is written specifically with Bittrex in mind, which uses some strange conventions, for example the reverse order of pairs. On most exchanges the format is `BaseCurrency/QuoteCurrency`, where `QuoteCurrency` is typically BTC. Bittrex is even weirder in that it represents that it names QuoteCurrency as BaseCurrency, and BaseCurrency as MarketCurrency in the API, which has been used in the code. We should probably change references to `base_currency` in the code to `quote_currency` to adhere to common usage.

Binance is only the default in the sense that it is the default value in the config, and used for tests as well as fetching backtesting data. In principle changing `binance` to `bittrex` in the config should make the bot usable on Bittrex. Which exchange to use for fetching backtesting data could also be moved into the config, depending on the available markets. Bittrex has a 20 day history limit and Binance has a 500 item limit, but allows specifying a date range. So by doing multiple fetches and joining the data we could download longer spans.

@glonlas ccxt would replace the current API structure, which uses a common interface and specific implementations for each exchange. This is already part of ccxt, which already presents a common interface.

**Comment by enenn** [comment]
Also, whenever you feel that this can be merged into gcarq/ccxt-in-use, go ahead, so others can contribute as well. I might not have very much time to continue working on it at the moment.

**Comment by enenn** [comment]
Exchange module now catches all exceptions from ccxt and wraps them in either a `OperationalException`, `DependencyException` or `NetworkException`, as well as adds some additional information. This way the rest of the project is not dependent on catching ccxt exception classes.

**Comment by ElanHasson** [comment]
Is this ready for use?

**Comment by xmatthias** [comment]
just had a look at the branch in @enenn's repository  - doesn't seem to be completely ready, backtesting hardcodes Binance as exchange (making it impossible to use any other exchange while backtesting).

**Comment by xmatthias** [comment]
Additional question - is there a reason to keep stake_currency limited to ['BTC', 'ETH', 'USDT']?
i think with the integration of ccxt, it's easily possible to support USD or EUR as well by removing / extending the list of allowed  stake_currencies in misc.py

**Comment by ElanHasson** [comment]
how exactly do you set the config for ccxt branch?

For example, GDAX uses an APIKey, Secret, and Passphrase..

**Comment by enenn** [comment]
Thanks for the comments @xmatthias and @ElanHasson . Good catches! :) I've been a bit busy with exams but I'll take a look at it tomorrow. Exchange shouldn't be hardcoded as you said but should be fetched from config. I don't see any reason to limit stake currency either. Passphrase should be added to the config.

**Comment by shusso** [comment]
Not my PR, but I think in the beginning we will only support bittrex&binance with ccxt. When we have proven that those work, we can start to support more exchanges.

**Comment by enenn** [comment]
Taking a look at this now in the light of day.

> backtesting hardcodes Binance as exchange (making it impossible to use any other exchange while backtesting).

>how exactly do you set the config for ccxt branch? For example, GDAX uses an APIKey, Secret, and Passphrase.

I will fix this by pulling exchange from config and adding passphrase to config. Exchange is used in backtesting for getting fees and historical data in live-data mode. Not all exchanges support fetching historical data from their API so perhaps we could find some solution where a default exchange is used if the selected exchange does not support it. But I'll leave that for now.

> is there a reason to keep stake_currency limited to ['BTC', 'ETH', 'USDT']?

There is no support yet for making trades in a NANO/BTC market if NANO is your stake currency, for example. It is required that the Quote currency (the last currency in the pair) is the stake currency. Since BTC, ETH, and USDT are available as a quote currency on most exchanges I think I will leave this as it is, to not cause any confusion if someone tries to use a different stake currency. Feels a bit out of scope of this PR as well.

> Not my PR, but I think in the beginning we will only support bittrex&binance with ccxt. When we have proven that those work, we can start to support more exchanges.

Yeah this is probably a good idea. Will add limits to config.

**Comment by xmatthias** [comment]
hi @enenn,
I've been doing some work lately on this branch as well, trying to get the outstanding stuff to work. 
However, I'm not quite sure if merging the ccxt-in-use branch in this repository, or the branch in your account is the right approach.
in the Slack channel I've been told that the branch in this repository from @shusso is going to be "the thing" - but looking at this discussion I'm not so certain about that anymore.

**Comment by enenn** [comment]
Hey @xmatthias,

I assume this PR from my repo will be merged into gcarq/feat/ccxt-in-use, and then that will be merged into develop but I see there has been some work on feat/ccxt-in-use in parallel as well. When I created this PR I didn't intent for it to be the final ccxt implementation, but that it would be merged into feat/ccxt-in-use as a work in progress so other people could continue to work on it. 

Any thoughts on this @shusso?

**Comment by xmatthias** [comment]
hi @enenn,
i got a question - I noticed that your version converts OHLCV from ccxt to the json format used in freqbot, while the branch here uses it "as is" from ccxt.
The conversation to the freqtrade format is a unnecessary conversion in my opinion, ccxt does unify the format for this already.

As to which ccxt exchanges can/should be supported - each ccxt exchange has a "has" attribute showing it's capabilities - as long as we use "base" methods and this is implemented, it should work and return an expected result in my understanding of ccxt. This beeing said - upon initialising, we should check the "has" attribute for a list of things freqbot needs in order to work correctly.

source: [ccxt manual](https://github.com/ccxt/ccxt/wiki/Manual)

**Comment by enenn** [comment]
@xmatthias 
>i got a question - I noticed that your version converts OHLCV from ccxt to the json format used in freqbot, while the branch here uses it "as is" from ccxt.
The conversation to the freqtrade format is a unnecessary conversion in my opinion, ccxt does unify the format for this already.

You could use the raw format from ccxt but I converted it to a format similar to the old one to make it more human readable. It doesn't cost too much disk space and you can compress the files with gz if necessary.

> As to which ccxt exchanges can/should be supported - each ccxt exchange has a "has" attribute showing it's capabilities

Yep. I think the point of starting with only 2 exchanges is to avoid lots of issues that might arise from different exchanges when running live, which makes testing and debugging harder. Once we can get 2 exchanges working we can more on to more. The bot is still struggling to get the same performance on one exchange as in backtesting.

**Comment by xmatthias** [comment]
my point was not the disk space it consumes - but the (unnecessary?) conversion (ccxt converts once, the bot converts again).
keeping the old format does simplify the transition to ccxt though, so i agree with you.

good points on the exchanges. 

> the above being said - I like the work on your branch and would suggest to have it merged to the ccxt-in-use branch ASAP - as it would fix a ton of stuff i intended to work on to get it "ready".
@shusso @enenn any comments on the above?

**Comment by xmatthias** [comment]
@ElanHasson the limiting is "for now" - as currently noone tested the ccxt branch "wet" yet - so until it can run without problems making real buy/sell orders without problems it does not make sense to spread out the testing to 20 exchanges ccxt would support.

In theory, all fully implemented ccxt exchanges shoudl be supported - but currently difficult to maintain.

@enenn there is a bug in main.py - [check_handle_timeout]
(https://github.com/enenn/freqtrade/blob/feat/ccxt-in-use/freqtrade/main.py#L208-L212)
fetch_order from ccxt does not contain a 'opened' field - but either [datetime or timestamp](https://github.com/ccxt/ccxt/blob/master/python/ccxt/bittrex.py#L527-L543)

**Comment by xmatthias** [comment]
@enenn quick feedback:
get_ticker has a problem with the _TICKER_CACHE variable - it should be a dict / set per pair (at least that's how it is in the develop branch).
I currently test-run the bot from your branch with multiple pairs, and get very odd percentages on open orders as the bid is always the same for all 3 orders (but with ETH and IOTA the rates are VERY different, resulting in either a 7000% loss, or 7000% win (or similar).

**Comment by siedi** [comment]
Testing the branch with another exchange (bitmex), the get_ticker_history needs to set the `since` parameter in the `fetch_ohlcv` as well, as otherwise, the 100 candles might not be the latest ones but start somewhere in the past (depending on the exchange I think).

https://github.com/enenn/freqtrade/blob/5178b469afd8e018c919ef66123403035bde30dc/freqtrade/exchange/__init__.py#L223

**Comment by xmatthias** [comment]
should we close this PR? it's not going to get merged since objectify was merged, and we now have a better, newer version of this PR (#603)

**Comment by enenn** [comment]
Yes, closing it.

**Pull request closed without merging**
