### PR TITLE
Feature (experimental): Add force profit sell param

### PR DESCRIPTION
**Pull request by glonlas**
Have you been upset with the bot when your selling strategy sells a trade with a big loss (e.g -29%)?
Did you wonder if you could force the bot to retain a losing trade until it goes up later (days, weeks)?

This PR solve this issue by adding an experimental parameter to force the bot to not sell trade that will generate a loss.

## New config parameter "sell_profit_only"
In the `config.json` within the `experimental` list, you can enable or disable the feature "Sell with profit only".

**Default value in the config**
```json
"experimental": {
        ...
        "sell_profit_only": false
    },
```

## Logic in detail
The logic implemented in this PR is very simple

In `main.py::handle_trade()` a new rule forces the bot to ignore a sell if the profit is negative.
```python
# Experimental: Check if the trade is profitable before selling it (avoid selling at loss)
    if _CONF.get('experimental', {}).get('sell_profit_only'):
        logger.debug('Checking if trade is profitable ...')
        if trade.calc_profit(rate=current_rate) <= 0:
            return False
```

## Unitests
This PR integrates unitests that test this feature.

## Need PR #200 to be merged
This PR work with or without the PR#200. However, the unitest are made to be compliant with the PR#200. Read, they pass with the PR#200, and will probably fail without (Because of the mock ticker price used in unitest to simulate profit and loss)

### CODE REVIEW

**Comment by glonlas** [comment]
Only the last commit eb47646 is part of this PR. The 2 other commits are the PR#200

**Comment by gcarq** [comment]
@glonlas I'm not sure about this PR, maybe I missed something. I know what it tries to solve, but `main::min_roi_reached()` should already do that. IMO `stoploss` should be optional, then you shouldn't have any loss sells.

**Comment by glonlas** [comment]
I agree with you about the stoploss that can be optional. The issue is the sell strategy can define valid a trade with a lower closing price than te open price. This is why sometime I got -45%. 

I am not also very convinced by my solution, this is why I put it as experimental until someone can teach me how to do better :)

**Comment by glonlas** [comment]
This PR was moved to https://github.com/glonlas/freqtrade/pull/1

**Pull request closed without merging**
