### PR TITLE
Linter fixes

### PR DESCRIPTION
**Pull request by vertti**
This PR fixes a bunch of fairly trivial warnings from PyLint linter. Easiest to review commit-by-commit.

### CODE REVIEW

**Comment by vertti** [comment]
Hello @gcarq . We like your bot and would love to help take it to the next level. We will be actively developing our fork and would like to send you the PR's, but the longer they are unmerged on your repo, the harder it gets to create and merge the PRs.

Please let us know if you are interested in getting more PR's to your bot or if we should just go on with our own fork.

**Comment by gcarq** [comment]
Thanks a lot! I'm happy to merge future PR's, I will do my best to merge them in a timely manner. What are your plans to take it to the next level?

cheers,
Michael

**Comment by vertti** [comment]
Rough initial ideas:

- `asyncio` for running more queries to bittrex in parallel or maybe with websocket when that is available
- separate the buying and selling so they can be run in parallel too
- more indicators aside from MACD & StochRSI, maybe volume/volatility etc.
- way to benchmark/simulate changes to indicators, like taking historical data and see how the bids/sells would have performed
- adding enough unit testing to bullet proof the basic functionality

**Comment by gcarq** [comment]
Sounds very nice, I'm looking forward to it

**Pull request merged**
