### PR TITLE
Completed parallel-searching generator

### PR DESCRIPTION
**Pull request by MoonGem**
Code is PEP8 compliant.

## Summary
Replace hyperopt with a parallel-searching random strategy generator that can search for profitable strategies as a modification to the bot.

Solve the issue: Slow hyperopt, possibly all hyperopt issues if hyperopt is removed.

## Quick changelog

Added files:

```	
README.md
backtesting.py
bittrex.py
config.json
default_strategy.py
generator.py
pp-1.6.4.4.zip
```
I can remove bittrex.py but I use it personally for the api key error handling.

## What's new?

Documentation on custom strategies.

Parallel backtesting with parallel python giving you the ability to connect to remote nodes to run backtesting functions. Note: ROI and Timeframe random options as well as EMA/SMA options are not randomized as these are likely set to those values for a given reason.

What's randomized:

Triggers all combinations.

ADX 1-100

MFI 1-100

RSI 1-100

FASTD 1-100

It's like hyperopt, except, takes advantage of the cores available to you.

### CODE REVIEW

**Comment by vertti** [comment]
But it is not "like hyperopt", it is random. Hyperopt uses several algorithms that make it much much faster in finding solutions than random values. Even with just your 5 variables, that search space is 100 million evaluations. And because it's random, you have no idea if you've found a good solution with a smaller subset.

On the other hand, I would love to get rid of Hyperopt. How long does a full search space take with your solution?

**Comment by gcarq** [comment]
Whats the reason behind duplicating `backtesting.py`, `bittrex.py` and `default_strategy.py`. What is `pp-1.6.4.4.zip`?

**Comment by MoonGem** [comment]
@gcarq Well, It was mostly just a mod I coded, it took me a few days because my python knowledge is pretty rusty. pp.zip is a parallel processing module. You can connect to servers and run remote python code as long as the imports are available and code is available on remote servers.

I edited backtesting.py because I was having trouble connecting to the logger in the freqtrade code, as an alternative I just print out the total profit, check if its greater than the last random parameter, and print out the parameters.


bittrex.py was modified so I wouldn't get api key errors and crash the bot, worked fine :)

default_strategy is in place because the -s option wouldn't work even if I defined the class, it contains the ramdom generator for parameters in a function called select() and prints them out, where generator.py runs them all in threads (in my case across 32 cores) or more depending if I setup python on remote servers and connect this way into the parallel processing pool.

@vertti Thanks, this answers some information I was curious about hyperopt. But I read somewhere that the parameters it supplies are completely random. At any rate, the processing does not work right with mongodb. Mongodb returns all loss as infinite for some reason.

My best reccomendation is to implement rayTune as it's threaded and heavily supported here on github. I tried to code parameters for it, but failed pretty badly. 

:) Thanks for your guys's input. This was a fun project nontheless.

**Comment by vertti** [comment]
Only first few values are random, those are used to calibrate the algorithm (Tree of Parzen Estimators (TPE)) used by Hyperopt. If you have trouble getting sleep, read this https://www.lri.fr/~kegl/research/PDFs/BeBaBeKe11.pdf :)

**Comment by MoonGem** [comment]
@vertti Thanks for the input :)

Now I've got hyperopt running n parallel, I should have went that route!!!!!

**Pull request closed without merging**
